# -*- coding: utf-8 -*-
"""Exercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivZshpSN2k8sL-6UQl4qnT3VVj1qEUKm
"""

#1. Faça um programa que peça um valor monetário e diminua-o em 15%. Seu programa deve imprimir a mensagem “O novo valor é [valor]”.

valor = input("Informe o valor: ")
valor = float(valor)

valor = valor-(15/100)
print("O novo valor é: ",valor)

#2. Faça um programa que leia a validade das informações:
#a. Idade: entre 0 e 150;
#b. Salário: maior que 0;
#c. Sexo: M, F ou Outro;
#O programa deve imprimir uma mensagem de erro para cada informação inválida.

Idade = int(input("Informe sua idade: "))
if Idade >= 0 and Idade <= 150:
  print("Informação idade válida!")
else:
  print("Informação idade inválida!")

Salario = input ("Informe seu salário R$: ")
Salario = float(Salario)
if Salario > 0:
  print("Informação salário válida!")
else:
  print("Informação salário inválida!")


Sexo = input("Informe seu sexo, M, F ou Outro: ")

if Sexo == "M":
  print("Informação sexo válida!") 
elif Sexo == "F":
  print("Informação sexo válida!")
elif Sexo == "Outro":
  print("Informação sexo válida!")
else:
  print("Informação sexo inválida!")